### ISSUE TITLE
Some quick questions

### ISSUE THREAD

**Issue by cwillforeal** [e-mo/rfm69_rp2040#1]
Hi! This a great library thank you so much for putting this much work into it. I'm looking to get started using it and was wondering if there is any example code using this library. I'm sure I could get there eventually but maybe another project using the RUDP would be helpful.
Again I appreciate any examples you might be able to point me to.

Cheers

**Comment by e-mo** [comment]
Hello! I've been been dragging my feet a bit on finishing the documentation and examples. I'll aim to get you an RUDP example by the end of today or tomorrow. Thanks for using the library!

**Comment by cwillforeal** [comment]
Thank you for writing it! I look forward to using it! Cheers

**Comment by e-mo** [comment]
I pushed some basic rx/tx rudp examples. I don't have any hardware to test on at the moment, but I will test tomorrow. Let me know if you have any troubles!

**Comment by e-mo** [comment]
I sat down with a pair of radios and debugged the example. I made a few changes to the API in the process so the first version I posted wasn't working but my test radios are currently talking using the example code. Enjoy!

**Comment by cwillforeal** [comment]
Thank you! One of radios went out so waiting on a replacement. Looking forward to getting it running!
